# Generated by Django 4.2.7 on 2023-11-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('Technology', 'Technology'), ('Health and Wellness', 'Health and Wellness'), ('Food and Beverage', 'Food and Beverage'), ('Retail', 'Retail'), ('Other', 'Other')], max_length=50)),
                ('target_market', models.TextField()),
                ('unique_selling_proposition', models.TextField()),
                ('specific_requirements', models.TextField()),
                ('goals_and_objectives', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
