# Generated by Django 4.2.7 on 2023-11-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BizPlan_App', '0004_feedback_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactResponse',
        ),
    ]
